### ISSUE TITLE
DeviceEngagedException: Cannot find any available device for your request

### ISSUE THREAD

**Issue by AkshitDunzo** [testvagrant/Ekam-Template#3]
**Describe the bug**
We have test cases ~250, 1/3 of the tests are getting skipped because of the DeviceEngagedException. We have total no of devices 10 devices on browserstack out of which we are trying to use only 5 at a time. We are using 4 thread to run parallel test and simultaneously 1 thread for sequential test.

**To Reproduce**
1. Run Higher number of test Parallel on Browserstack.

**Expected behavior**
Ekam should allocate device to all the test.

**Screenshots**
<img width="1396" alt="Screenshot 2022-02-01 at 12 13 28 PM" src="https://user-images.githubusercontent.com/88654169/151923888-745ba86d-300d-4485-95e2-ecdea30d9a7a.png">

**Smartphone (please complete the following information):**
 - Device: OnePlus 8, Google Pixel 4XL, Samsung Galaxy s20, OnePlus 7T
 - OS: Android 10

**Comment by Prajwalgn-07** [comment]
@AkshitDunzo can u provide the stack trace

**Comment by AkshitDunzo** [comment]
Unable to create injector, see the following errors:

1) [Guice/ErrorInCustomProvider]: DeviceEngagedException: Cannot find any available device for your request, please try after sometime
  while locating MobileDriverDetailsProvider
  at MobileModule.configure(MobileModule.java:15)
  while locating MobileDriverDetails

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: DeviceEngagedException: Cannot find any available device for your request, please try after sometime
	at DeviceCache.get(DeviceCache.java:96)
	at DeviceManager.getAvailableDevice(DeviceManager.java:29)
	at BrowserStackDeviceFinder.findDevice(BrowserStackDeviceFinder.java:34)
	at BrowserStackDriver.findTarget(BrowserStackDriver.java:59)
	at BrowserStackDriver.buildRemoteMobileConfig(BrowserStackDriver.java:31)
	at RemoteMobileDriverFactory.remoteMobileDriverFactory(RemoteMobileDriverFactory.java:19)
	at MobileDriverDetailsProvider.createRemoteDriver(MobileDriverDetailsProvider.java:40)
	at MobileDriverDetailsProvider.get(MobileDriverDetailsProvider.java:34)
	at MobileDriverDetailsProvider.get(MobileDriverDetailsProvider.java:26)
	at ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at BoundProviderFactory.get(BoundProviderFactory.java:59)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at InjectorImpl.createChildInjector(InjectorImpl.java:239)
	at EkamInjector.createInjector(EkamInjector.java:51)
	at EkamMobileInjector.create(EkamMobileInjector.java:15)
	at com.testvagrant.ekam.testBases.cucumber.MobileScenarioDefinition.setup(MobileScenarioDefinition.java:20)
	at MobileCucumberHooks.setup(MobileCucumberHooks.java:31)
	at GeneratedMethodAccessor266.invoke(Unknown Source)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:566)
	at Invoker.doInvoke(Invoker.java:66)
	at Invoker.invoke(Invoker.java:24)
	at AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at JavaHookDefinition.execute(JavaHookDefinition.java:59)
	at CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at ExecutionMode$1.execute(ExecutionMode.java:10)
	at TestStep.executeStep(TestStep.java:92)
	at TestStep.run(TestStep.java:64)
	at TestCase.run(TestCase.java:98)
	at Runner.runPickle(Runner.java:73)
	at TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:134)
	at CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:131)
	at CustomTestNGCucumberTests.runScenario(CustomTestNGCucumberTests.java:46)
	at GeneratedMethodAccessor218.invoke(Unknown Source)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:566)
	at MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at TestInvoker.invokeMethod(TestInvoker.java:598)
	at TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/FutureTask.run(FutureTask.java:264)
	at java.base/Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/FutureTask.run(FutureTask.java:264)
	at java.base/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/Thread.run(Thread.java:829)

2) [Guice/ErrorInCustomProvider]: DeviceEngagedException: Cannot find any available device for your request, please try after sometime
  while locating MobileDriverDetailsProvider
  at MobileModule.configure(MobileModule.java:15)
  at AppiumDriverProvider.<init>(AppiumDriverProvider.java:14)
      \_ for 1st parameter
  while locating AppiumDriverProvider
  at MobileModule.configure(MobileModule.java:19)
  while locating AppiumDriver<MobileElement>

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER
Caused by: DeviceEngagedException: Cannot find any available device for your request, please try after sometime
	at DeviceCache.get(DeviceCache.java:96)
	at DeviceManager.getAvailableDevice(DeviceManager.java:29)
	at BrowserStackDeviceFinder.findDevice(BrowserStackDeviceFinder.java:34)
	at BrowserStackDriver.findTarget(BrowserStackDriver.java:59)
	at BrowserStackDriver.buildRemoteMobileConfig(BrowserStackDriver.java:31)
	at RemoteMobileDriverFactory.remoteMobileDriverFactory(RemoteMobileDriverFactory.java:19)
	at MobileDriverDetailsProvider.createRemoteDriver(MobileDriverDetailsProvider.java:40)
	at MobileDriverDetailsProvider.get(MobileDriverDetailsProvider.java:34)
	at MobileDriverDetailsProvider.get(MobileDriverDetailsProvider.java:26)
	at ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
	at BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
	at BoundProviderFactory.get(BoundProviderFactory.java:59)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at ConstructorInjector.provision(ConstructorInjector.java:113)
	at ConstructorInjector.construct(ConstructorInjector.java:91)
	at ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at BoundProviderFactory.get(BoundProviderFactory.java:58)
	at ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at SingletonScope$1.get(SingletonScope.java:169)
	at InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at InjectorImpl.createChildInjector(InjectorImpl.java:239)
	at EkamInjector.createInjector(EkamInjector.java:51)
	at EkamMobileInjector.create(EkamMobileInjector.java:15)
	at com.testvagrant.ekam.testBases.cucumber.MobileScenarioDefinition.setup(MobileScenarioDefinition.java:20)
	at MobileCucumberHooks.setup(MobileCucumberHooks.java:31)
	at GeneratedMethodAccessor266.invoke(Unknown Source)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:566)
	at Invoker.doInvoke(Invoker.java:66)
	at Invoker.invoke(Invoker.java:24)
	at AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at JavaHookDefinition.execute(JavaHookDefinition.java:59)
	at CoreHookDefinition.execute(CoreHookDefinition.java:46)
	at HookDefinitionMatch.runStep(HookDefinitionMatch.java:21)
	at ExecutionMode$1.execute(ExecutionMode.java:10)
	at TestStep.executeStep(TestStep.java:92)
	at TestStep.run(TestStep.java:64)
	at TestCase.run(TestCase.java:98)
	at Runner.runPickle(Runner.java:73)
	at TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:134)
	at CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:131)
	at CustomTestNGCucumberTests.runScenario(CustomTestNGCucumberTests.java:46)
	at GeneratedMethodAccessor218.invoke(Unknown Source)
	at java.base/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/Method.invoke(Method.java:566)
	at MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at TestInvoker.invokeMethod(TestInvoker.java:598)
	at TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
	at TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
	at java.base/FutureTask.run(FutureTask.java:264)
	at java.base/Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/FutureTask.run(FutureTask.java:264)
	at java.base/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/Thread.run(Thread.java:829)

2 errors

======================
Full classname legend:
======================
AbstractGlueDefinition:                 "io.cucumber.java.AbstractGlueDefinition"
AppiumDriver:                           "io.appium.java_client.AppiumDriver"
AppiumDriverProvider:                   "com.testvagrant.ekam.mobile.providers.AppiumDriverProvider"
BoundProviderFactory:                   "com.google.inject.internal.BoundProviderFactory"
BrowserStackDeviceFinder:               "com.testvagrant.ekam.devicemanager.devicefinder.BrowserStackDeviceFinder"
BrowserStackDriver:                     "com.testvagrant.ekam.mobile.remote.BrowserStackDriver"
ConstructorBindingImpl$Factory:         "com.google.inject.internal.ConstructorBindingImpl$Factory"
ConstructorInjector:                    "com.google.inject.internal.ConstructorInjector"
CoreHookDefinition:                     "io.cucumber.core.runner.CoreHookDefinition"
CucumberExecutionContext:               "io.cucumber.core.runtime.CucumberExecutionContext"
CustomTestNGCucumberTests:              "com.dunzo.CustomTestNGCucumberTests"
DelegatingMethodAccessorImpl:           "jdk.internal.reflect.DelegatingMethodAccessorImpl"
DeviceCache:                            "com.testvagrant.ekam.devicemanager.DeviceCache"
DeviceEngagedException:                 "com.testvagrant.ekam.devicemanager.exceptions.DeviceEngagedException"
DeviceManager:                          "com.testvagrant.ekam.devicemanager.DeviceManager"
EkamInjector:                           "com.testvagrant.ekam.internal.injectors.EkamInjector"
EkamMobileInjector:                     "com.testvagrant.ekam.internal.injectors.EkamMobileInjector"
ExecutionMode$1:                        "io.cucumber.core.runner.ExecutionMode$1"
Executors$RunnableAdapter:              "java.util.concurrent.Executors$RunnableAdapter"
FutureTask:                             "java.util.concurrent.FutureTask"
GeneratedMethodAccessor218:             "jdk.internal.reflect.GeneratedMethodAccessor218"
GeneratedMethodAccessor266:             "jdk.internal.reflect.GeneratedMethodAccessor266"
HookDefinitionMatch:                    "io.cucumber.core.runner.HookDefinitionMatch"
InjectorImpl:                           "com.google.inject.internal.InjectorImpl"
InternalFactoryToProviderAdapter:       "com.google.inject.internal.InternalFactoryToProviderAdapter"
InternalInjectorCreator:                "com.google.inject.internal.InternalInjectorCreator"
Invoker:                                "io.cucumber.java.Invoker"
JavaHookDefinition:                     "io.cucumber.java.JavaHookDefinition"
Method:                                 "java.lang.reflect.Method"
MethodInvocationHelper:                 "org.testng.internal.MethodInvocationHelper"
MobileCucumberHooks:                    "com.dunzo.mobile.user_app.steps.MobileCucumberHooks"
MobileDriverDetails:                    "com.testvagrant.ekam.mobile.models.MobileDriverDetails"
MobileDriverDetailsProvider:            "com.testvagrant.ekam.mobile.providers.MobileDriverDetailsProvider"
MobileElement:                          "io.appium.java_client.MobileElement"
MobileModule:                           "com.testvagrant.ekam.mobile.modules.MobileModule"
ProviderInternalFactory:                "com.google.inject.internal.ProviderInternalFactory"
ProviderToInternalFactoryAdapter:       "com.google.inject.internal.ProviderToInternalFactoryAdapter"
RemoteMobileDriverFactory:              "com.testvagrant.ekam.mobile.remote.RemoteMobileDriverFactory"
Runner:                                 "io.cucumber.core.runner.Runner"
SingleParameterInjector:                "com.google.inject.internal.SingleParameterInjector"
SingletonScope$1:                       "com.google.inject.internal.SingletonScope$1"
TestCase:                               "io.cucumber.core.runner.TestCase"
TestInvoker:                            "org.testng.internal.TestInvoker"
TestMethodWithDataProviderMethodWorker: "org.testng.internal.TestMethodWithDataProviderMethodWorker"
TestNGCucumberRunner:                   "io.cucumber.testng.TestNGCucumberRunner"
TestStep:                               "io.cucumber.core.runner.TestStep"
ThreadPoolExecutor:                     "java.util.concurrent.ThreadPoolExecutor"
ThreadPoolExecutor$Worker:              "java.util.concurrent.ThreadPoolExecutor$Worker"
========================
End of classname legend:
========================

@Prajwalgn-07

**Comment by Prajwalgn-07** [comment]
Update **ekam device manager version to 1.0.2-beta**
