### ISSUE TITLE
When ran web test in headless, screenshot move failed

### ISSUE THREAD

**Issue by amit-decathlon** [testvagrant/Ekam-Template#5]
**Describe the bug**
When web test ran in headless mode, the screenshot capture failed with below issue

**To Reproduce**
Run 1 web test in headless mode

**Expected behavior**
Test case should run successfully with capturing screenshot

**Desktop (please complete the following information):**
 - OS : mac
 - Browser : chrome
 - Version : 98.0

**Additional context**
logs : 

`java.lang.RuntimeException:` Cannot move screenshot.
/var/folders/1n/b02_rwkx7g184pt84bw2y_1c0000gn/T/screenshot14754857501638838668.png -> /Users/amityerva/IdeaProjects/DOSA-EKAM-AUTOMATION/build/ekam-execution-timeline/com.dosa.ekam.web.tests.cart.happypath.CartTests/validateUserCanUpdatePinCodeFromCartScreen/screenshots/2022-02-08T10:40:37.711854.png	at com.testvagrant.ekam.internal.executiontimeline.EkamTestScreenshotTaker.captureScreenshot(EkamTestScreenshotTaker.java:43)
	at com.testvagrant.ekam.commons.LayoutInitiator.captureScreenshot(LayoutInitiator.java:39)
	at com.testvagrant.ekam.reports.interceptors.WebStepInterceptor.addStep(WebStepInterceptor.java:32)
	at com.testvagrant.ekam.reports.interceptors.WebStepInterceptor.invoke(WebStepInterceptor.java:19)
	at com.dosa.ekam.web.actions.ProductStep.proceedToCartStep(ProductStep.java:21)
	at com.dosa.ekam.web.actions.WebStep.proceedToCartStep(WebStep.java:50)`

**Comment by amit-decathlon** [comment]
This is observed when 2 set of test cases ran parallel. Hence capture failed. 
Will post here if faced this issue in future
